### ISSUE TITLE
Please document *why* there's documentation on disabling certificate checking

### ISSUE THREAD

**Issue by joshtriplett** [rusoto/rusoto.github.io#128]
The existence of https://rusoto.org/disable-ssl-cert-check.html is disconcerting, doubly so because it doesn't start and end with a giant disclaimer of "You don't want to do this. Here's the very narrow circumstance that motivated us to add this documentation.". Also, that documentation suggests connecting to AWS that way, rather than (for instance) some private service. Could you please provide such information/motivation, to make it clear why this is a thing anyone would need to do and why it was documented?

**Comment by matthewkmayer** [comment]
While disabling SSL/TLS certificate validation is a common scenario, you're correct: the page should include the standard "this is not recommended, only use if you understand this is insecure and do not use it for talking to real AWS services" disclaimer.

The original request for this behavior is https://github.com/rusoto/rusoto/issues/1277 : using local simulators or implementations of AWS APIs with self-signed certificates.

An example of an API compatible service documenting using self signed certs: https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html .

Official AWS SDKs and tooling provide this opt-in behavior as well:
* [Go SDK](https://github.com/aws/aws-sdk-go/issues/2404)
* [Java SDK](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#DISABLE_CERT_CHECKING_SYSTEM_PROPERTY)
* [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/)

The page on https://rusoto.org should:
* [ ] add a warning about when this behavior is appropriate
* [ ] change the example to use localhost instead of a real AWS endpoint

Any other questions about the behavior or page?

**Comment by joshtriplett** [comment]
Changing the example to localhost, and making it clear that this is *only* for testing, would help make it clear that this is only for testing. Thank you.
