### ISSUE TITLE
README: explain use of branches

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#16]
`source` and `master` doesn't quite fit standard git branching names (github flow, git flow, trunk based development, etc..).  Let's update the README to call out how the branches differ and how they're used.

**Comment by indiv0** [comment]
Well I wasn't sure what to call the branch with the markdown source, but I decided on `source` as at least a temporary measure. It's a more or less correct name. `master` isn't used as it is typically on GitHub, but that's because we want the generated site to go there since GitHub Pages only publishes from `master` on organization repository pages. Everything else is standard.

I think I'll just edit the above a little and add it in.
