### ISSUE TITLE
API docs not accessible via rusoto.org

### ISSUE THREAD

**Issue by srijs** [rusoto/rusoto.github.io#76]
Hi!

Not sure if this is related to #67, but the S3 bucket that the rusoto API docs are served from seems to deny access when trying to access it via https://rusoto.org/rusoto/rusoto/, while accessing the docs via https://rusoto.github.io/rusoto/ works (which looks like it's hosted via github pages?).

**Comment by matthewkmayer** [comment]
Thanks for checking on this.

All API docs are on Github pages.  Rusoto.org does not contain API docs.  If you found a link to API docs on rusoto.org I'd love to hear where so I can fix it. 😉 

The access denied error from https://rusoto.org/rusoto/rusoto/ is expected behavior as it's not in the bucket.

**Comment by srijs** [comment]
Seems like this was my mistake, somewhere I started assuming rusoto.org and rusoto.github.io would be hosting the same content. Closing.
