### ISSUE TITLE
Add example of S3 Select

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#99]
Let's document how to use S3 Select and Rusoto! https://github.com/rusoto/rusoto/issues/1092 is an issue where our support for it isn't clear. An example will help with that and running it through `skeptic` will ensure it stays correct. 👍

**Comment by alex-berger** [comment]
I wanted to use the [select_object_content](https://rusoto.github.io/rusoto/rusoto_s3/trait.S3.html#tymethod.select_object_content) method, so I started studing the API, ...

According to the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html) and to other SDK (e.g. [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.select_object_content)), this method is supposed to return a `Stream` of events. However, the rusoto API looks like it returns just one single event (and **not** a `Stream`).
The method currently looks like this:
```rust
fn select_object_content(
    &self, 
    input: SelectObjectContentRequest
) -> RusotoFuture<SelectObjectContentOutput, SelectObjectContentError>
```
And the output types look like this:

```rust
pub struct SelectObjectContentOutput {
    pub payload: Option<SelectObjectContentEventStream>,
}
```
```rust
pub struct SelectObjectContentEventStream {
    pub cont: Option<ContinuationEvent>,
    pub end: Option<EndEvent>,
    pub progress: Option<ProgressEvent>,
    pub records: Option<RecordsEvent>,
    pub stats: Option<StatsEvent>,
}
```

Now, I am really confused (or it's because it is Friday). Am I to stupid to grasp how this API is supposed to work or is it just not yet implemented correctly? If the latter is true then rusoto/rusoto#1092 is actually not solved and this needs more than just documentation.

**Comment by matthewkmayer** [comment]
I posted some findings and a link to a code sample in https://github.com/rusoto/rusoto/issues/1092 . Turns out we have some more to implement for S3-Select to work with Rusoto.

**Comment by matthewkmayer** [comment]
Since this isn't implemented in Rusoto, we can't make an example for it yet. 😢
